### PR TITLE
Passing objects when selection changes

### PR DESCRIPTION
**Pull request by omriyariv**
When changing selection in the Selector components it will now pass the object that corresponds to the selected option, instead of passing the ID only.

This is useful for doing
 ```jsx
const data = [{
  id: 1,
  payload: 'foo'
}, {
  id: 2,
  payload: 'bar'
}]
<Selector data={data} onChange={(obj) => console.log(obj.payload)}> 
```

### CODE REVIEW

**Comment by yuval-netanel** [comment]
:+1

**Comment by joaomilho** [comment]
Cool, but note master is now on React 15 and w/ new Fields. We'll either need to update our app and test properly or publish a version on 0.7.x.

**Comment by omriyariv** [comment]
Closing this PR without merging to master. v0.7.4 was tagged on this branch. I'll implement the same changes on master once we adopt the latest release in MyKlarna (React 15 and all).

**Comment by joaomilho** [comment]
Sababa.

**Pull request closed without merging**
