### PR TITLE
Use new default margins from CSS components

### PR DESCRIPTION
**Pull request by xaviervia**
Only showing the example from `SecondaryTitle` since they all look more or less the same and it's pretty long.

An open question is how to name the prop, since `defaultMargins` doesn't ring quite right.

This will be major version bump BTW

screen shot 2016-06-14 at 17 57 58

### CODE REVIEW

**Comment by JoakimLofgren** [comment]
Well, I dunno what else to call it either.. block spacing? paragraph margin? text spacing?

**Comment by xaviervia** [comment]
Yeah there was no strong suggestion either way. Let's merge, we can rename later if it's really necessary. This property should be slowly phased out once we have the template components.

**Comment by xaviervia** [comment]
I'll rename the flag to be just `margins` following @cskeppstedt suggestion, since `defaultMargins` is not the best description.

**Comment by Deschtex** [comment]
Should the CSS components class also be called just `margin`? :- )

**Comment by xaviervia** [comment]
I'll add an alias in the CSS components to support either `default-margins` or just `margins` as the class. Don't want to make another major version bump.

https://github.com/klarna/ui-css-components/issues/45

**Pull request merged**
