### PR TITLE
Updated the css component version to support ie9 fields

### PR DESCRIPTION
**Pull request by alexanderlindholm**
I updated the css component version to the latest one to get fixes for ie9 fields

### CODE REVIEW

**Comment by Nevon** [comment]
Might want to bump this one to 6.5.2, since that also fixes some other stuff.

**Comment by alexanderlindholm** [comment]
I upgraded the version of the css components to 6.5.2

**Comment by Nevon** [comment]
Travis timed out while attempting to run the tests on Android. I don't know if there is a way to trigger a retry (at least I couldn't find one), but you could always do the age old trick of pushing an empty commit: ` git commit --allow-empty -m "If at first you don't succeed, try again"`

**Comment by Nevon** [comment]
Found it!

**Pull request merged**
